authors = ["William Herrera <wherrera@alahonua.com>"]
name = "BackedUpImmutable"
uuid = "ce7fb557-0848-50b6-86d3-b63d1ee2efee"
version = "0.0.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
julia = "1"

[targets]
test = ["Pkg", "Test"]
